### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [tobiaszimmer/ofxHersheyFont#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by tobiaszimmer** [comment]
Hey, there are no easy and satisfying ways to convert an exisiting font into a single line font. A quick search for "persian single line font" also yielded no results, sorry! I guess you have to create your own font with a vector software.
